/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1p2_rafaelajuria;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rajur
 */
public class GUI extends javax.swing.JFrame {
    static ArrayList<Usuario> Usuarios = new ArrayList();
    static ArrayList<Libro> Libros = new ArrayList();
    static int LoggedInUser=-1;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog_CreateAccount = new javax.swing.JDialog();
        jPanel_CeateAccount = new javax.swing.JPanel();
        jLabelTXT_CrearUsuario = new javax.swing.JLabel();
        jLabelTXT_NewUsername = new javax.swing.JLabel();
        jTextField_NewUsername = new javax.swing.JTextField();
        jTextField_NewPassword = new javax.swing.JTextField();
        jLabelTXT_NewPassword = new javax.swing.JLabel();
        jTextField_NewDOB = new javax.swing.JTextField();
        jLabelTXT_NewDOB = new javax.swing.JLabel();
        jTextField_NewNumber = new javax.swing.JTextField();
        jLabelTXT_NewNumber = new javax.swing.JLabel();
        jTextField_NewEmail = new javax.swing.JTextField();
        jLabelTXT_NewEmail = new javax.swing.JLabel();
        jTextField_NewNombre = new javax.swing.JTextField();
        jLabelTXT_NewNombre = new javax.swing.JLabel();
        jLabelTXT_GeneroFavorito = new javax.swing.JLabel();
        jRadioButton_NewGenero_Fantasia = new javax.swing.JRadioButton();
        jRadioButton_NewGenero_Acion = new javax.swing.JRadioButton();
        jRadioButton_NewGenero_Romance = new javax.swing.JRadioButton();
        jButton_CrearUsuarioNuevo = new javax.swing.JButton();
        buttonGroup_NewGenero = new javax.swing.ButtonGroup();
        jFrame_MainMenu = new javax.swing.JFrame();
        jPanel_MainMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_VerLibros = new javax.swing.JButton();
        jButton_AdminMenu = new javax.swing.JButton();
        jButton_SacarLibros = new javax.swing.JButton();
        jButton_DevolverLibros = new javax.swing.JButton();
        jButton_PrestarLibro = new javax.swing.JButton();
        jButton_AgregarAmigo = new javax.swing.JButton();
        jButton_Recomendados = new javax.swing.JButton();
        jButton_CerrarSesion = new javax.swing.JButton();
        jFrame_VerLibros = new javax.swing.JFrame();
        jScrollPane_Libros = new javax.swing.JScrollPane();
        jTable_Libros = new javax.swing.JTable();
        jPanel_VerLibros = new javax.swing.JPanel();
        jLabelTXT_Inventario = new javax.swing.JLabel();
        jFrame_AdministradorDeLibros = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_LibrosEnExistencia = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_LibrosDelUsuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel_AdministradorDeLibros = new javax.swing.JLabel();
        jButton_SacarLibro = new javax.swing.JButton();
        jButton_DevolverLibro = new javax.swing.JButton();
        jFrame_LibrosRecomendados = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_LibrosRecomendados = new javax.swing.JTable();
        jFrame_Amigos = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel_LoginScreen = new javax.swing.JPanel();
        jLabelTXT_IniciarSesion = new javax.swing.JLabel();
        jLabelTXT_Username = new javax.swing.JLabel();
        jLabelTXT_Password = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jButton_CrearCuenta = new javax.swing.JButton();
        jButton_Login = new javax.swing.JButton();

        jPanel_CeateAccount.setBackground(java.awt.SystemColor.activeCaption);

        jLabelTXT_CrearUsuario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelTXT_CrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTXT_CrearUsuario.setText("Crear Usuario Nuevo");

        javax.swing.GroupLayout jPanel_CeateAccountLayout = new javax.swing.GroupLayout(jPanel_CeateAccount);
        jPanel_CeateAccount.setLayout(jPanel_CeateAccountLayout);
        jPanel_CeateAccountLayout.setHorizontalGroup(
            jPanel_CeateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CeateAccountLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelTXT_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel_CeateAccountLayout.setVerticalGroup(
            jPanel_CeateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CeateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTXT_CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelTXT_NewUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewUsername.setText("Nombre de Usuario:");

        jLabelTXT_NewPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewPassword.setText("Contraseña:");

        jLabelTXT_NewDOB.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewDOB.setText("Fecha de Nacimiento:");

        jLabelTXT_NewNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewNumber.setText("Numero de Telefono:");

        jLabelTXT_NewEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewEmail.setText("Correo Electronico:");

        jLabelTXT_NewNombre.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_NewNombre.setText("Nombre Completo:");

        jLabelTXT_GeneroFavorito.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTXT_GeneroFavorito.setText("Genero Favorito:");

        buttonGroup_NewGenero.add(jRadioButton_NewGenero_Fantasia);
        jRadioButton_NewGenero_Fantasia.setText("Fantasia");

        buttonGroup_NewGenero.add(jRadioButton_NewGenero_Acion);
        jRadioButton_NewGenero_Acion.setText("Accion");

        buttonGroup_NewGenero.add(jRadioButton_NewGenero_Romance);
        jRadioButton_NewGenero_Romance.setText("Romance");

        jButton_CrearUsuarioNuevo.setText("Crear");
        jButton_CrearUsuarioNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearUsuarioNuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialog_CreateAccountLayout = new javax.swing.GroupLayout(jDialog_CreateAccount.getContentPane());
        jDialog_CreateAccount.getContentPane().setLayout(jDialog_CreateAccountLayout);
        jDialog_CreateAccountLayout.setHorizontalGroup(
            jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_CeateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabelTXT_NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabelTXT_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabelTXT_NewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabelTXT_NewNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NewNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addComponent(jLabelTXT_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                        .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelTXT_GeneroFavorito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelTXT_NewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_NewGenero_Romance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_NewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_NewGenero_Fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_NewGenero_Acion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton_CrearUsuarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDialog_CreateAccountLayout.setVerticalGroup(
            jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_CreateAccountLayout.createSequentialGroup()
                .addComponent(jPanel_CeateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewUsername)
                    .addComponent(jTextField_NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewPassword)
                    .addComponent(jTextField_NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewDOB)
                    .addComponent(jTextField_NewDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewNumber)
                    .addComponent(jTextField_NewNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewEmail)
                    .addComponent(jTextField_NewEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_NewNombre)
                    .addComponent(jTextField_NewNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_GeneroFavorito)
                    .addComponent(jRadioButton_NewGenero_Fantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_NewGenero_Acion)
                    .addComponent(jRadioButton_NewGenero_Romance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CrearUsuarioNuevo)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel_MainMenu.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setBackground(java.awt.SystemColor.activeCaption);
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Principal");

        javax.swing.GroupLayout jPanel_MainMenuLayout = new javax.swing.GroupLayout(jPanel_MainMenu);
        jPanel_MainMenu.setLayout(jPanel_MainMenuLayout);
        jPanel_MainMenuLayout.setHorizontalGroup(
            jPanel_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainMenuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_MainMenuLayout.setVerticalGroup(
            jPanel_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton_VerLibros.setText("Ver Libros en Inventario");
        jButton_VerLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_VerLibrosMouseClicked(evt);
            }
        });

        jButton_AdminMenu.setText("Menu de Admin");

        jButton_SacarLibros.setText("Sacar Libros");
        jButton_SacarLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SacarLibrosMouseClicked(evt);
            }
        });

        jButton_DevolverLibros.setText("Devolver Libros");
        jButton_DevolverLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_DevolverLibrosMouseClicked(evt);
            }
        });

        jButton_PrestarLibro.setText("Prestar Libro a Amigo");

        jButton_AgregarAmigo.setText("Agregar Amigos");

        jButton_Recomendados.setText("Recomendaciones");
        jButton_Recomendados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_RecomendadosMouseClicked(evt);
            }
        });

        jButton_CerrarSesion.setText("Cerrar Sesion");

        javax.swing.GroupLayout jFrame_MainMenuLayout = new javax.swing.GroupLayout(jFrame_MainMenu.getContentPane());
        jFrame_MainMenu.getContentPane().setLayout(jFrame_MainMenuLayout);
        jFrame_MainMenuLayout.setHorizontalGroup(
            jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                        .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                                .addComponent(jButton_AdminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_VerLibros)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                                .addComponent(jButton_SacarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_DevolverLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                        .addComponent(jButton_PrestarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_AgregarAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton_Recomendados, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton_CerrarSesion)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFrame_MainMenuLayout.setVerticalGroup(
            jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_MainMenuLayout.createSequentialGroup()
                .addComponent(jPanel_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AdminMenu)
                    .addComponent(jButton_VerLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_SacarLibros)
                    .addComponent(jButton_DevolverLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_PrestarLibro)
                    .addComponent(jButton_AgregarAmigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Recomendados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_CerrarSesion)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTable_Libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulos", "Autor", "Copias", "Genero"
            }
        ));
        jScrollPane_Libros.setViewportView(jTable_Libros);

        jPanel_VerLibros.setBackground(java.awt.SystemColor.activeCaption);

        jLabelTXT_Inventario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelTXT_Inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTXT_Inventario.setText("Inventario");

        javax.swing.GroupLayout jPanel_VerLibrosLayout = new javax.swing.GroupLayout(jPanel_VerLibros);
        jPanel_VerLibros.setLayout(jPanel_VerLibrosLayout);
        jPanel_VerLibrosLayout.setHorizontalGroup(
            jPanel_VerLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_VerLibrosLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabelTXT_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_VerLibrosLayout.setVerticalGroup(
            jPanel_VerLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTXT_Inventario, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame_VerLibrosLayout = new javax.swing.GroupLayout(jFrame_VerLibros.getContentPane());
        jFrame_VerLibros.getContentPane().setLayout(jFrame_VerLibrosLayout);
        jFrame_VerLibrosLayout.setHorizontalGroup(
            jFrame_VerLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_VerLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane_Libros, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
        jFrame_VerLibrosLayout.setVerticalGroup(
            jFrame_VerLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_VerLibrosLayout.createSequentialGroup()
                .addComponent(jPanel_VerLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTable_LibrosEnExistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Copias", "Edicion"
            }
        ));
        jScrollPane1.setViewportView(jTable_LibrosEnExistencia);

        jTable_LibrosDelUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Copias", "Edicion"
            }
        ));
        jScrollPane2.setViewportView(jTable_LibrosDelUsuario);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel_AdministradorDeLibros.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel_AdministradorDeLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_AdministradorDeLibros.setText("Administrar Libros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel_AdministradorDeLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_AdministradorDeLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jButton_SacarLibro.setText("Sacar Libro");
        jButton_SacarLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_SacarLibroMouseClicked(evt);
            }
        });

        jButton_DevolverLibro.setText("Devolver Libro");

        javax.swing.GroupLayout jFrame_AdministradorDeLibrosLayout = new javax.swing.GroupLayout(jFrame_AdministradorDeLibros.getContentPane());
        jFrame_AdministradorDeLibros.getContentPane().setLayout(jFrame_AdministradorDeLibrosLayout);
        jFrame_AdministradorDeLibrosLayout.setHorizontalGroup(
            jFrame_AdministradorDeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_AdministradorDeLibrosLayout.createSequentialGroup()
                .addGroup(jFrame_AdministradorDeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_AdministradorDeLibrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SacarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jFrame_AdministradorDeLibrosLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_DevolverLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_AdministradorDeLibrosLayout.setVerticalGroup(
            jFrame_AdministradorDeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_AdministradorDeLibrosLayout.createSequentialGroup()
                .addGroup(jFrame_AdministradorDeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame_AdministradorDeLibrosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_SacarLibro))
                .addGap(18, 18, 18)
                .addGroup(jFrame_AdministradorDeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_DevolverLibro))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recomendaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable_LibrosRecomendados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Copias", "Edicion"
            }
        ));
        jScrollPane3.setViewportView(jTable_LibrosRecomendados);

        javax.swing.GroupLayout jFrame_LibrosRecomendadosLayout = new javax.swing.GroupLayout(jFrame_LibrosRecomendados.getContentPane());
        jFrame_LibrosRecomendados.getContentPane().setLayout(jFrame_LibrosRecomendadosLayout);
        jFrame_LibrosRecomendadosLayout.setHorizontalGroup(
            jFrame_LibrosRecomendadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame_LibrosRecomendadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame_LibrosRecomendadosLayout.setVerticalGroup(
            jFrame_LibrosRecomendadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LibrosRecomendadosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Amigos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Usuario", "Fecha de Nacimiento"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout jFrame_AmigosLayout = new javax.swing.GroupLayout(jFrame_Amigos.getContentPane());
        jFrame_Amigos.getContentPane().setLayout(jFrame_AmigosLayout);
        jFrame_AmigosLayout.setHorizontalGroup(
            jFrame_AmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jFrame_AmigosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame_AmigosLayout.setVerticalGroup(
            jFrame_AmigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_AmigosLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel_LoginScreen.setBackground(java.awt.SystemColor.activeCaption);

        jLabelTXT_IniciarSesion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabelTXT_IniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTXT_IniciarSesion.setText("Iniciar Sesion");

        javax.swing.GroupLayout jPanel_LoginScreenLayout = new javax.swing.GroupLayout(jPanel_LoginScreen);
        jPanel_LoginScreen.setLayout(jPanel_LoginScreenLayout);
        jPanel_LoginScreenLayout.setHorizontalGroup(
            jPanel_LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LoginScreenLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabelTXT_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel_LoginScreenLayout.setVerticalGroup(
            jPanel_LoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTXT_IniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        jLabelTXT_Username.setText("Nombre de Usuario:");

        jLabelTXT_Password.setText("Contraseña:");

        jButton_CrearCuenta.setText("Crear Cuenta");
        jButton_CrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_CrearCuentaMouseClicked(evt);
            }
        });

        jButton_Login.setText("Iniciar Sesion");
        jButton_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_LoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_LoginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTXT_Password)
                            .addComponent(jLabelTXT_Username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Username)
                            .addComponent(jPasswordField_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_LoginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_Username)
                    .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTXT_Password)
                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CrearCuenta)
                    .addComponent(jButton_Login))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearCuentaMouseClicked
        // TODO add your handling code here:
        jDialog_CreateAccount.setVisible(true);
        jDialog_CreateAccount.setBounds(0, 0, 290, 370);
    }//GEN-LAST:event_jButton_CrearCuentaMouseClicked

    //Crear Usuario Nuevo
    private void jButton_CrearUsuarioNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CrearUsuarioNuevoMouseClicked
        // TODO add your handling code here:
        String Username = jTextField_NewUsername.getText();
        String Password = jTextField_NewPassword.getText();
        String DOB = jTextField_NewDOB.getText();
        int Numero = Integer.valueOf(jTextField_NewNumber.getText());
        String Email = jTextField_NewEmail.getText();
        String Nombre = jTextField_NewNombre.getText();
        String GeneroFav;
        //
        if(jRadioButton_NewGenero_Acion.isSelected())//Accion esta mal escrito :c Lo siento
        {
            GeneroFav="Accion";
        }
        else if(jRadioButton_NewGenero_Romance.isSelected())
        {
            GeneroFav="Romance";
        }
        else if(jRadioButton_NewGenero_Fantasia.isSelected())
        {
            GeneroFav="Fantasia";
        }
        else
        {
            GeneroFav="Ninguno";
        }
        //
        ArrayList<Usuario> Amigos = new ArrayList();
        ArrayList<Libro> LibrosLeidos = new ArrayList();
        Usuarios.add(new Usuario(Username,Password,DOB,Numero,Email,Nombre,GeneroFav,LibrosLeidos,Amigos));
        JOptionPane.showMessageDialog(null,"Usuario Creado"+Usuarios.get(Usuarios.size()-1));
        jTextField_NewUsername.setText("");
        jTextField_NewPassword.setText("");
        jTextField_NewDOB.setText("");
        jTextField_NewNumber.setText("");
        jTextField_NewEmail.setText("");
        jTextField_NewNombre.setText("");
        jDialog_CreateAccount.setVisible(false);
    }//GEN-LAST:event_jButton_CrearUsuarioNuevoMouseClicked

    private void jButton_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_LoginMouseClicked
        // TODO add your handling code here:
        LoggedInUser=-1;
        String Username = jTextField_Username.getText();
        String Password =jPasswordField_Password.getText();
        for(int i=0; i<Usuarios.size();i++)
        {
            if(Usuarios.get(i).getUsername().equals(Username))
            {
                if(Usuarios.get(i).getPassword().equals(Password))
                {
                    LoggedInUser=i;
                }
            }
        }
        if(LoggedInUser!=-1)
        {
          JOptionPane.showMessageDialog(null,"Bienvenido, "+Usuarios.get(LoggedInUser).getNombre());
          jFrame_MainMenu.setVisible(true);
          jFrame_MainMenu.setBounds(0, 0, 339, 267);
        }
        else
        {
         JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrectos.");   
        }
    }//GEN-LAST:event_jButton_LoginMouseClicked

    private void jButton_VerLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_VerLibrosMouseClicked
        // TODO add your handling code here:
        jFrame_VerLibros.setVisible(true);
        jFrame_VerLibros.setBounds(0,0,600,250);
        for(int i=0;i<Libros.size();i++)
        {
            jTable_Libros.setValueAt(Libros.get(i).getTitulo(), i, 0);
            jTable_Libros.setValueAt(Libros.get(i).getAutor(), i, 1);
            jTable_Libros.setValueAt(Libros.get(i).getCopias(), i, 2);
            jTable_Libros.setValueAt(Libros.get(i).getGenero(), i, 3);
        }
    }//GEN-LAST:event_jButton_VerLibrosMouseClicked

    private void jButton_SacarLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SacarLibrosMouseClicked
        // TODO add your handling code here:
        jFrame_AdministradorDeLibros.setVisible(true);
        jFrame_AdministradorDeLibros.setBounds(0, 0, 583, 273);
        for(int i=0;i<Libros.size();i++)
        {
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getTitulo(), i, 0);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getAutor(), i, 1);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getCopias(), i, 2);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getGenero(), i, 3);
        }
        for(int i=0;i<Usuarios.get(LoggedInUser).getLibrosLeidos().size();i++)
        {
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getTitulo(), i, 0);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getAutor(), i, 1);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getCopias(), i, 2);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getGenero(), i, 3);
        }
    }//GEN-LAST:event_jButton_SacarLibrosMouseClicked

    private void jButton_DevolverLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_DevolverLibrosMouseClicked
        // TODO add your handling code here:
        jFrame_AdministradorDeLibros.setVisible(true);
        jFrame_AdministradorDeLibros.setBounds(0, 0, 583, 273);
        for(int i=0;i<Libros.size();i++)
        {
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getTitulo(), i, 0);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getAutor(), i, 1);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getCopias(), i, 2);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getGenero(), i, 3);
        }
        for(int i=0;i<Usuarios.get(LoggedInUser).getLibrosLeidos().size();i++)
        {
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getTitulo(), i, 0);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getAutor(), i, 1);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getCopias(), i, 2);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getGenero(), i, 3);
        }
    }//GEN-LAST:event_jButton_DevolverLibrosMouseClicked

    private void jButton_SacarLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_SacarLibroMouseClicked
        // TODO add your handling code here:
        int LibroASacar=Integer.parseInt(JOptionPane.showInputDialog("Introduzca la posicion del libro que desea sacar"));
        try
        {
            Usuarios.get(LoggedInUser).getLibrosLeidos().add(Libros.get(LibroASacar));
            Usuarios.get(LoggedInUser).getLibrosLeidos().get(Usuarios.get(LoggedInUser).getLibrosLeidos().size()-1).setCopias(1);
            Libros.get(LibroASacar).setCopias((Libros.get(LibroASacar).getCopias())-1);
            for(int i=0;i<Libros.size();i++)
        {
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getTitulo(), i, 0);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getAutor(), i, 1);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getCopias(), i, 2);
        jTable_LibrosEnExistencia.setValueAt(Libros.get(i).getGenero(), i, 3);
        }
        for(int i=0;i<Usuarios.get(LoggedInUser).getLibrosLeidos().size();i++)
        {
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getTitulo(), i, 0);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getAutor(), i, 1);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getCopias(), i, 2);
        jTable_LibrosDelUsuario.setValueAt(Usuarios.get(LoggedInUser).getLibrosLeidos().get(i).getGenero(), i, 3);
        }
        } catch(ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null,"Error. Posicion Incorrecta");
        }
    }//GEN-LAST:event_jButton_SacarLibroMouseClicked

    private void jButton_RecomendadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RecomendadosMouseClicked
        // TODO add your handling code here:
        jFrame_LibrosRecomendados.setVisible(true);
        jFrame_LibrosRecomendados.setBounds(0,0,468, 157);
        for(int i=0;i<Libros.size();i++)
        {
            if(Libros.get(i).getGenero().equals(Usuarios.get(LoggedInUser).getGeneroFavorito()))
            {
             jTable_LibrosRecomendados.setValueAt(Libros.get(i).getTitulo(), i, 0);
             jTable_LibrosRecomendados.setValueAt(Libros.get(i).getAutor(), i, 1);
             jTable_LibrosRecomendados.setValueAt(Libros.get(i).getCopias(), i, 2);
             jTable_LibrosRecomendados.setValueAt(Libros.get(i).getGenero(), i, 3);
            }
        }
    }//GEN-LAST:event_jButton_RecomendadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Create the default users and books
        Usuarios.add(new Usuario("admin","12345","1/1/1900",11223344,"admin@programa.com","Administrador de Programa","Ninguno",new ArrayList(), new ArrayList()));
        Libros.add(new Libro("The Mortal Instruments: City of Bones","-----",5,7,"Fantasia",70.70,1,"Cassandra Clare",2007));
        Libros.add(new Libro("The Mortal Instruments: City of Ashes","-----",4,7,"Fantasia",40.70,1,"Cassandra Clare",2008));
        Libros.add(new Libro("The Mortal Instruments: City of Glass","-----",3,7,"Fantasia",60.70,1,"Cassandra Clare",2009));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_NewGenero;
    private javax.swing.JButton jButton_AdminMenu;
    private javax.swing.JButton jButton_AgregarAmigo;
    private javax.swing.JButton jButton_CerrarSesion;
    private javax.swing.JButton jButton_CrearCuenta;
    private javax.swing.JButton jButton_CrearUsuarioNuevo;
    private javax.swing.JButton jButton_DevolverLibro;
    private javax.swing.JButton jButton_DevolverLibros;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_PrestarLibro;
    private javax.swing.JButton jButton_Recomendados;
    private javax.swing.JButton jButton_SacarLibro;
    private javax.swing.JButton jButton_SacarLibros;
    private javax.swing.JButton jButton_VerLibros;
    private javax.swing.JDialog jDialog_CreateAccount;
    private javax.swing.JFrame jFrame_AdministradorDeLibros;
    private javax.swing.JFrame jFrame_Amigos;
    private javax.swing.JFrame jFrame_LibrosRecomendados;
    private javax.swing.JFrame jFrame_MainMenu;
    private javax.swing.JFrame jFrame_VerLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelTXT_CrearUsuario;
    private javax.swing.JLabel jLabelTXT_GeneroFavorito;
    private javax.swing.JLabel jLabelTXT_IniciarSesion;
    private javax.swing.JLabel jLabelTXT_Inventario;
    private javax.swing.JLabel jLabelTXT_NewDOB;
    private javax.swing.JLabel jLabelTXT_NewEmail;
    private javax.swing.JLabel jLabelTXT_NewNombre;
    private javax.swing.JLabel jLabelTXT_NewNumber;
    private javax.swing.JLabel jLabelTXT_NewPassword;
    private javax.swing.JLabel jLabelTXT_NewUsername;
    private javax.swing.JLabel jLabelTXT_Password;
    private javax.swing.JLabel jLabelTXT_Username;
    private javax.swing.JLabel jLabel_AdministradorDeLibros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_CeateAccount;
    private javax.swing.JPanel jPanel_LoginScreen;
    private javax.swing.JPanel jPanel_MainMenu;
    private javax.swing.JPanel jPanel_VerLibros;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JRadioButton jRadioButton_NewGenero_Acion;
    private javax.swing.JRadioButton jRadioButton_NewGenero_Fantasia;
    private javax.swing.JRadioButton jRadioButton_NewGenero_Romance;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane_Libros;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Libros;
    private javax.swing.JTable jTable_LibrosDelUsuario;
    private javax.swing.JTable jTable_LibrosEnExistencia;
    private javax.swing.JTable jTable_LibrosRecomendados;
    private javax.swing.JTextField jTextField_NewDOB;
    private javax.swing.JTextField jTextField_NewEmail;
    private javax.swing.JTextField jTextField_NewNombre;
    private javax.swing.JTextField jTextField_NewNumber;
    private javax.swing.JTextField jTextField_NewPassword;
    private javax.swing.JTextField jTextField_NewUsername;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
